# Linear regression:


In [ ]:
import numpy as np

class LinearRegression:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        # 1. Setup dimensions
        n_samples, n_features = X.shape

        # 2. Initialize weights to 0
        self.weights = np.zeros(n_features)
        self.bias = 0

        # 3. Gradient Descent Loop
        for _ in range(self.n_iters):

            # Step A: Predict (y = wx + b)
            y_predicted = np.dot(X, self.weights) + self.bias

            # Step B: Calculate Gradients (Direction to move)
            # dw = (1/N) * X.T * (pred - real)
            loss = y_predicted - y 
            dw = (1 / n_samples) * (np.dot(X.T, (y_predicted - y)) + 2 * self.l2_constant * np.sum(self.weights))
            # db = (1/N) * sum(pred - real)
            db = (1 / n_samples) * np.sum(y_predicted - y)

            # Step C: Update Parameters
            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self, X):
        return np.dot(X, self.weights) + self.bias

# --- Usage Example ---
if __name__ == "__main__":
    # Data: Number of hours studied vs Exam Score
    # X needs to be a 2D array (samples, features)
    X = np.array([[1], [2], [3], [4], [5]])
    y = np.array([2, 4, 6, 8, 10]) # The pattern is y = 2x

    model = LinearRegression(learning_rate=0.01, n_iters=1000)
    model.fit(X, y)

    # Predict score for studying 6 hours
    test_X = np.array([[6]])
    prediction = model.predict(test_X)

    print(f"Prediction for 6 hours: {prediction[0]:.2f}") # Should be close to 12
    print(f"Equation: y = {model.weights[0]:.2f}x + {model.bias:.2f}")


In [6]:
np.zeros(5).shape

(5,)

In [ ]:
# KNN code
#convert to class
#run for multiple test dataset:
class oknn():
    # def __init__(self):
    def knn(X,Y,queryPoints,k):
        # Euclidean Distance

        for query in queryPoints:
            queryPoint = query
            dist = np.sqrt(np.sum((queryPoint-X)**2,axis=1) )



            # Storing distance and Class labels together

            distances = [(dist[i],Y[i]) for i in range(len(dist)) ]

            # sort the distances
            #(2.1,1), ((1.6,1)), (4.5,0)
            distances = sorted(distances)

            # Nearest/First K points

            distances = distances[:k]



            distances = np.array(distances)

            classes_counts = np.unique(distances[:,1],return_counts=True)



            index = classes_counts[1].argmax()

            pred = classes_counts[0][index]



            return int(pred),distances

In [20]:
x = np.arange(10).reshape(2, 5)
x , x.sum(axis = 1) , x.sum(axis = 0)

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([10, 35]),
 array([ 5,  7,  9, 11, 13]))

In [ ]:
import numpy as np

class KNNClassifier:
    def __init__(self, k=3):
        """
        Initialize the KNN model.
        :param k: The number of neighbors to consider (hyperparameter).
        """
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        """
        Store the training data.
        Since KNN is a 'lazy learner', this doesn't learn weights,
        it just memorizes the data.
        """
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        print(f"Model fitted with {len(self.X_train)} training samples.")

    def predict(self, X_test):
        """
        Predict class labels for one or more query points.
        :param X_test: A list or array of query points.
        :return: Array of predicted labels.
        """
        X_test = np.array(X_test)

        # If X_test is a single point (1D array), make it 2D so loop works
        if X_test.ndim == 1:
            X_test = X_test.reshape(1, -1)

        # Loop through every point in the test set and predict
        predictions = [self._predict_single_point(x) for x in X_test]

        return np.array(predictions)

    def _predict_single_point(self, query_point):
        """
        Internal helper function to run the logic for a single point.
        (This contains the core logic from your original script).
        """
        # 1. Euclidean Distance
        # (query_point - all_training_points)
        distances = np.sqrt(np.sum((query_point - self.X_train)**2, axis=1))

        # 2. Storing distance and Class labels together
        # We zip the distances with the training labels
        dist_label_pairs = list(zip(distances, self.y_train))

        # 3. Sort by distance (first item in tuple)
        sorted_pairs = sorted(dist_label_pairs)

        # 4. Nearest K points
        k_nearest_pairs = sorted_pairs[:self.k]

        

        # 5. Extract just the labels from those K pairs
        k_nearest_labels = [label for dist, label in k_nearest_pairs]

        # 6. Majority Vote (using NumPy unique)
        classes, counts = np.unique(k_nearest_labels, return_counts=True)

        # Find index of max count
        max_count_index = counts.argmax()

        # Return the winning class
        return classes[max_count_index]

# --- Usage Example ---

if __name__ == "__main__":
    # 1. Define Dataset (Redness, Roundness) -> 0:Apple, 1:Banana
    X_train = [[1, 1], [1, 2], [2, 1], [5, 5], [5, 6], [6, 5]]
    y_train = [0, 0, 0, 1, 1, 1]

    # 2. Initialize Model
    model = KNNClassifier(k=3)

    # 3. Fit Model (Load data)
    model.fit(X_train, y_train)

    # 4. Predict
    # Let's test a point that is [2, 2] (should be Apple/0)
    # and a point that is [6, 6] (should be Banana/1)
    query_points = [[2, 2], [6, 6]]

    predictions = model.predict(query_points)

    print(f"\nTest Points: {query_points}")
    print(f"Predictions: {predictions}") # Expected: [0 1]

In [ ]:
#distance weighted knn
import numpy as np
import pandas as pd
class KNNClassifier:
    def __init__(self, k=3):
        """
        Initialize the KNN model.
        :param k: The number of neighbors to consider (hyperparameter).
        """
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        """
        Store the training data.
        Since KNN is a 'lazy learner', this doesn't learn weights,
        it just memorizes the data.
        """
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        print(f"Model fitted with {len(self.X_train)} training samples.")

    def predict(self, X_test):
        """
        Predict class labels for one or more query points.
        :param X_test: A list or array of query points.
        :return: Array of predicted labels.
        """
        X_test = np.array(X_test)

        # If X_test is a single point (1D array), make it 2D so loop works
        if X_test.ndim == 1:
            X_test = X_test.reshape(1, -1)

        # Loop through every point in the test set and predict
        predictions = [self._predict_single_point(x) for x in X_test]

        return np.array(predictions)

break    def _predict_single_point(self, query_point):
        """
        Internal helper function to run the logic for a single point.
        (This contains the core logic from your original script).
        """
        # 1. Euclidean Distance
        # (query_point - all_training_points)
        distances = np.sqrt(np.sum((query_point - self.X_train)**2, axis=1))

        # 2. Storing distance and Class labels together
        # We zip the distances with the training labels
        dist_label_pairs = list(zip(distances, self.y_train))

        # 3. Sort by distance (first item in tuple)
        sorted_pairs = sorted(dist_label_pairs)

        # 4. Nearest K points
        k_nearest_pairs = sorted_pairs[:self.k]
        df = pd.DataFrame(k_nearest_pairs , columns = ['distance' , 'class'])
        gdf = df.groupby('class').agg({'distance' : np.sum})
        gdf = gdf.sort_values(by = ['distance'])


        return gdf.iloc[0]['class']

# --- Usage Example ---

if __name__ == "__main__":
    # 1. Define Dataset (Redness, Roundness) -> 0:Apple, 1:Banana
    X_train = [[1, 1], [1, 2], [2, 1], [5, 5], [5, 6], [6, 5]]
    y_train = [0, 0, 0, 1, 1, 1]

    # 2. Initialize Model
    model = KNNClassifier(k=3)

    # 3. Fit Model (Load data)
    model.fit(X_train, y_train)

    # 4. Predict
    # Let's test a point that is [2, 2] (should be Apple/0)
    # and a point that is [6, 6] (should be Banana/1)
    query_points = [[2, 2], [6, 6]]

    predictions = model.predict(query_points)

    print(f"\nTest Points: {query_points}")
    print(f"Predictions: {predictions}") # Expected: [0 1]

In [ ]:
import tensorflow as tf
#Logistic Regression:
class LogisticR():
    def __init__(self , lr , niter):
        self.lr = lr
        self.niter = niter
        self.weights = None
        self.bias = None

    def fit(self , x , y):
        n , m = x.shape
        self.weights = np.zeros(m)
        self.bias = 0

        for i in range(self.lr):
            z = np.matmul(self.weights , x)
            logits = tf.nn.sigmoid(z)

            dlogloss = logits * (1 - logits)

            self.weights += self.lr * dlogloss

        return self.weights



    def predict(self , x):
        return tf.nn.sigmoid(np.matmul())




In [22]:
np.zeros(5).shape

(5,)

In [ ]:
#decision tree:
